### ISSUE TITLE
Data storage of plugin details

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#16]
When we will process the probes / rules, we will have to store a number of details on each plugin. 
In PostgreSQL, it is possible to store JSON data in a specific field. This would allow us to have some flexibility about the data we gather for each plugin.

 - Create a new field in Plugin class to store a key/value based data structure
 - Configure the project to create that field in the database

As a first usage, we can see that in the update-center JSON file, we have a list of deprecated plugins. Please store this detail in the newly create field.

Some links:
 - JSON data type in PostgreSQL: https://www.postgresql.org/docs/current/datatype-json.html
 - Mapping the data type to Java code: https://vladmihalcea.com/java-map-json-jpa-hibernate

**Comment by dheerajodha** [comment]
Here's what I have understood:

The issues ask us to create a new field in the Plugin class to store a key/value-based data structure and configure the project to make that field in the database as well (as you have written clearly).

After I do this, inside our Plugin table there would be a column where we can store a key-value JSON object.

What I do not understand is how this new addition would help us store the details that are currently stored inside the `deprecations` object of the update-center JSON file. Because the `deprecations` object is storing a map of this: `<pluginID>:<deprecation Notice URL>`.

**Question)** What is the intent of storing this in the Database?
I believe we want to use this object and store it (in some way) in our DB so that for each given plugin row inside our DB, we'll be able to answer this question: Is the current plugin deprecated?

Carrying the same understanding forward, why are we going with trying to store a JSON object in our database? why can't we have things like this?
![image](https://user-images.githubusercontent.com/43273420/176918133-1462e1e5-4b5e-4dea-ae6c-7f490409e6f8.png)


We can do this by traversing the `deprecations` object and for each "key" we are searching a row in our table with name=key, and then storing the "value" of that key inside the "deprecation status" column of the matched-plugin row.

With this, we can answer the question: is the current plugin deprecated? by checking if there is any value inside the "deprecation status" column of the row corresponding to the plugin in question.

I have a strong feeling that I'm missing something and I'm wrong. So, please correct me, thank you.

**Comment by alecharp** [comment]
> What is the intent of storing this in the Database? 

We could store the reason of the deprecation, this is a good point. But most importantly: any deprecated plugins shouldn't be analyzed until it is not deprecated anymore. Also, it should be considered as a "disqualifying" grade in my opinion.

> Carrying the same understanding forward, why are we going with trying to store a JSON object in our database?

Because, for some plugins, we might have "maven details", for others "gradle details". Many will have "source code details", when those without a valid SCM link won't. 

The JSON field will help us because we won't have to require a strict format for the details and still be able to query that field correctly. 

If we want to have one column per each "probe", then the database will quickly start to be hard to manage.

**Comment by dheerajodha** [comment]
Thank you Adrien for your explanation here and on the call, it cleared lots of doubts for me. And the problem statement of this issue makes sense to me.
