### ISSUE TITLE
Application Startup failure

### ISSUE THREAD

**Issue by impact-maker** [jenkins-infra/plugin-health-scoring#187]
Description 
Application was built and started running on localhost but encountered an error on the url localhost:8080/probes. 
Attaching the screenshot below:
![Screenshot from 2023-01-21 17-44-15](https://user-images.githubusercontent.com/86894399/213866402-86bd59ee-f57a-4aa5-9c4c-34ab430ad97d.png)

**Comment by alecharp** [comment]
Thanks for reporting this. Please note that a partial screenshot of the error might not be enough. Copying the logs would be better. However, in this case, I think the problem is because you didn't generate the `git.properties` or `build.properties`. This is done by Maven, with `mvn generate-resources` which is done if you compile the code before running `mvn spring-boot:run`.

Can you try that? Thanks.

**Comment by impact-maker** [comment]
@alecharp Its running fine now after applying the commands. Closing this issue for now.
