### ISSUE TITLE
GitHub API Rate limitation

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#22]
During the Probe Engine exploration (#19), I noticed that relying on the GitHub API wouldn't be a valid option. The call rate limitation is not enough to perform a simple analyze on all the plugins. 

We need to explore the usage of JGit to analyze the plugin repositories.

**Comment by dheerajodha** [comment]
I read about JGit and found out that it's a "pure Java library implementation of the Git". I'm trying to understand why with JGit we won't have any API Rate Limitation.

As per my understanding, since GitHub API is offered by the GitHub team, so they thought "let's put a limit on the number of requests they can send to our servers". And this introduced the rate-limiting problem to us. On the other hand, the JGit team studied algorithms and inner working of each git command and wrote everything from scratch using pure java, and created this library. So, this way GitHub team has no relationship with JGit, and therefore there's no problem with rate limits here.

Is this why we're using JGit?

**Comment by alecharp** [comment]
Using #33, we opened the road the not only depend on GitHub API to get details on the plugins. I consider this as addressed, even if it's a concern we need to keep in mind as some probes will only be able to be resolved using the API.
