### ISSUE TITLE
Add a `RenovateProbe` and `RenovatePullRequestProbe`

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-health-scoring#254]
### Description

Similar to `DependabotProbe`, I would like to propose the addition of a `RenovateProbe` (and therefore `DependabotPullRequestProbe` too).
Specific repositories use renovate instead of dependabot, especially repositories, which have multiple files to keep track of, or need other functionality, dependabot doesn't offer.

**Comment by alecharp** [comment]
This was mentioned in the past but didn't know any plugin using anything else that Dependabot. 

Do you have specific plugins which are using `Renovate`? What about `update-cli`, any plugin using this?

**Comment by NotMyFault** [comment]
There are a few ones using renovate: https://github.com/search?q=org%3Ajenkinsci+renovate.json&type=code

No plugins are using update cli that I am aware of.

**Comment by alecharp** [comment]
Thanks @NotMyFault. We will include this in a future release.

**Comment by alecharp** [comment]
Looking back at this, I'm not sure we need a `RenovatePullRequestProbe` as the pull request created by the bot have a label `dependencies`, like for Dependabot, which is what we are counting in https://github.com/jenkins-infra/plugin-health-scoring/blob/d2d54972f01badc653cc33016b8b90d3574411a1/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotPullRequestProbe.java#L58-L60. 

I guess is that the `DependabotPullRequestProbe` is not really well named because of that. But we will be able to use its result in combination of a new `RenovateProbe` in the scoring implementation.
