### ISSUE TITLE
Elastic axis score incorrectly says docs not in GitHub repo

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-health-scoring#285]
### Description of the bug

https://plugin-health.jenkins.io/scores/elastic-axis shows the "Documentation is not located in the plugin repository" even though the [plugins site](https://plugins.jenkins.io/elastic-axis/) shows the documentation from the [README.md](https://github.com/jenkinsci/elastic-axis-plugin#readme) in the plugin repository

**Comment by alecharp** [comment]
Thank you for reporting this! 
The problem seems to be that, the link to the documentation has a `/` at the end of the url. Because of this 

https://github.com/jenkins-infra/plugin-health-scoring/blob/b9133e157595e367696a390599847919f92f8b61/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DocumentationMigrationProbe.java#L51

is false, as the `scm` doesn't include that `/`.

This lead me to think that other plugins, using a more precise URL for the documentation (with a folder or a branch) won't work either.

Looking into this.
