### ISSUE TITLE
Possible false positive in `scm` probe of mailer-plugin

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-health-scoring#297]
### Description of the bug

The scm probe for the [mailer](https://plugin-health.jenkins.io/scores/mailer) plugin reports a bad result.
According to the pom.xml of the mailer plugin, the `<scm>` block follows a valid scheme:
https://github.com/jenkinsci/mailer-plugin/blob/f3acbe010bc54b77b82f981cec63df93b878cf5f/pom.xml#L144-L149

**Comment by alecharp** [comment]
Normally, this is not the source of the problem, because the SCM link is coming from the `update-center.actual.json` file, which has the value interpreted.
I believe this was a temporary problem but as the probe requires a new release to be executed it is not updated. This is something #270 (or similar) should tackle.

**Comment by alecharp** [comment]
I'm closing this for now as this was not seen since.
