### ISSUE TITLE
double negative ish on health scrore

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-health-scoring#393]
### Problem with this page

https://plugins.jenkins.io/ldap/healthscore/

### Expected behavior

> No commit in the last 4 years. 0%

0 percent sounds bad. But it seems like from the above checks that there is comments newer than 4 years ago. So this feels like the check is inverted, if the only commits are more than 4 years ago, then negative points.

I think the check should be "had commits more recent than 4 years ago" so it sticks with convention 

Or I'm wrong and it proves my point it's confusing

![Screenshot_20231025-232034](https://github.com/jenkins-infra/plugin-site/assets/110087/5fb13650-5fef-4445-b025-5d5ea9ec6792)

### Actual behavior

Na

**Comment by alecharp** [comment]
thanks for reporting this @halkeye (and @zbynek and @smerle33 for transferring the issue here).

> Or I'm wrong and it proves my point it's confusing

You are not wrong but still it is confusing. Once we see that the gap between the latest release and the latest commit is less than 6 months, we shouldn't try to see if there is less than a year between the two. And so on. 

There is a large problem in the `AdoptionScoring` implementation, which I think I resolved in #392.
I'll merge this and release the project so that we can get rid of this invalid information.
