### ISSUE TITLE
Need Improvment in the  status message symbol of the Probes Result.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#426]
### Description of the bug

We can improve the Status Message symbol for the Probe Result. It is not an optimal point to show green tick symbol when a plugin is need improvement for a specific probe. 

Example: 
<img width="1149" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/6d13ee3b-7395-4726-8e0c-471397313024">

When a plugin needed improvement the status symbol must show particular warning instead of clear green indication. 

**Impact**
* Increase the attraction of maintainers and developers to update the plugin. 
* Help to new contributors to identify the improvement in the plugin via visulation.

**Comment by alecharp** [comment]
It's green because we were able to get access to the plugin repository and that it has or not dependabot (in your example). 
Probes are not commenting on the fact that there is or not Dependabot configured (again in your example). Probes are just getting the facts.

Scorings are using the probe results (facts) to draw conclusions.
