### ISSUE TITLE
How to achieve 100% health score for jenkins plugin

### ISSUE THREAD

**Issue by rahuldarekar222** [jenkins-infra/plugin-health-scoring#454]
As we have released our own plugin to jenkins marketplace, we are wondering on how to achieve 100% health score for it.
we have followed the steps given by jenkins team to release the plugin and enabled CD on it.
but we are not able to understand what needs to be done for :
**Repository Configuration**
No dependency version manager bot are used on the plugin repository.

as its always 0%. we have checked the probe github repository.

Could you please he to resolve same?

**Comment by alecharp** [comment]
I'm sorry this is not clear. I'm working on a solution in #452.

In your case, it's because you haven't setup dependabot or renovate to handle the dependency version bump automatically. I know this is not always required (plugins can have no dependencies); I also have ideas to deal with that situation. 

Be aware that currently,  98% is already a very good score.

**Comment by alecharp** [comment]
so first, currently the maximum score is 98%.
However, I believe that you are speaking about the repository https://github.com/jenkinsci/secone-security-plugin, correct?

I can see that the repository has Dependabot configured. So I think you have found a bug in the application. I'm investigating.

**Comment by alecharp** [comment]
Thank you for your question as it lead me to see a bug in the code. 
I fixed it and will be releasing the application soon. Normally, the plugin will have a score of 100% soon.

**Comment by rahuldarekar222** [comment]
Thanks Adrien. Will check the score after you release the changes.
