### ISSUE TITLE
Docs: Need proper documentation to understand the working of plugin-health-scoring

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#455]
Need proper documentation to understand the working of plugin-health-scoring

**Comment by alecharp** [comment]
Hello. Could you elaborate the problem you are facing? I fail to understand.

**Comment by AayushSaini101** [comment]
> Hello. Could you elaborate the problem you are facing? I fail to understand.

@alecharp At present, there is no proper documentation where is the data of plugin is coming, no documentation of the order of plugins and the interaction, We need to show the HLD of the tool via documentation. How we configure the cron to test the changes these kind of things we can add

**Comment by alecharp** [comment]
> there is no proper documentation where is the data of plugin is coming

Have you looked at the architecture document. There are referenes of the pluigin repositories, which is where most of the data are coming.

> no documentation of the order of plugins

Because the order has no importance and the order of the execution in production is probably different than the one I have. Technically, they are in a `Stream` coming from the database, so index based order. The index depends on when the plugin was imported first.

> the interaction

what interation?

> We need to show the HLD of the tool via documentation.

How would that help https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/ARCHITECTURE.adoc?

> How we configure the cron to test the changes

https://github.com/jenkins-infra/plugin-health-scoring/blob/c665ce9b5b4a0782d2a5a291fe62ed9e9986315e/docs/ARCHITECTURE.adoc?plain=1#L39-L41.

**Comment by AayushSaini101** [comment]
> https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/ARCHITECTURE.ado
@alecharp Yes, the documentation is present, I am thinking to add some more images that help the understandability of the tool more , image like this
<img width="651" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/2708c969-9a81-419c-a5da-52cfb83f8c58">

**Comment by AayushSaini101** [comment]
> > https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/ARCHITECTURE.ado
> > @alecharp Yes, the documentation is present, I am thinking to add some more images that help the understandability of the tool more , image like this
> 
> <img alt="image" width="651" src="https://private-user-images.githubusercontent.com/60972989/303046595-2708c969-9a81-419c-a5da-52cfb83f8c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjE4ODgsIm5iZiI6MTcwNzMyMTU4OCwicGF0aCI6Ii82MDk3Mjk4OS8zMDMwNDY1OTUtMjcwOGM5NjktOWE4MS00MTljLWE1ZGEtNTJjZmI4M2Y4YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZjBlNzQ0MWFmOGQ4MjFjMzBhYTI5OTljMDFjNzlkZjAyZDU0YzA5YTg0ZTkxOWVjMjQ0MDU0ZTU1ZTliMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OxZ95ESjhycTOjPdYEdJ6SK09fKtNBfOk5sbXIbAxa4">

We can also add information about the probes in the tool as well. I have checked docs we don't have sufficient information about the exisiting probes.

**Comment by alecharp** [comment]
> > https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/ARCHITECTURE.ado
> > @alecharp Yes, the documentation is present, I am thinking to add some more images that help the understandability of the tool more , image like this
> 
> <img alt="image" width="651" src="https://private-user-images.githubusercontent.com/60972989/303046595-2708c969-9a81-419c-a5da-52cfb83f8c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjM0ODYsIm5iZiI6MTcwNzMyMzE4NiwicGF0aCI6Ii82MDk3Mjk4OS8zMDMwNDY1OTUtMjcwOGM5NjktOWE4MS00MTljLWE1ZGEtNTJjZmI4M2Y4YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMWJmM2FkN2Y3ZThjZGJmOGM2YTk4ODhmNWZmMzEwMmM2OWQ1NzJiYjY1ZTYzMmYzNDkxY2IzNGNlM2MwZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82Jus77Xi_ml40C7nBf7QePl3fLGUS9fbez1SHoQv8A">

This is explaining how the scores are available on the plugin-site. This is not to be added into this project documentation. 

> We can also add information about the probes in the tool as well. I have checked docs we don't have sufficient information about the existing probes.

Because I don't want to maintain a growing list of probes manually. If you want, we could see to generate the Javadoc of the project, but I don't want to include more than that. The maintenance cost is too high in my opinion.
